# hyprwm org vouch list

# Core

github:vaxerski
github:fufexan
github:notashelf
github:outfoxxed
github:pointerdilemma
github:vdawg-git

# Very trusted

github:gulafaran
github:erstarr
github:fxzzi
github:ujint34
github:kolayne
github:ikalco

# Third party, passed vouch

github:danielkrupinski
github:lritzdorf
github:dregu
github:andresilva
github:zacoons
github:mightyplaza
github:thejch
github:itsohen
github:zjeffer
github:alba4k
github:virtcode
github:aqa-ib
github:kam1k4dze
github:lionheartp
github:frebib

# Denounced

