# hyprwm org vouch list

# Core

github:vaxerski
github:fufexan
github:notashelf
github:outfoxxed
github:pointerdilemma
github:vdawg-git

# Very trusted

github:gulafaran
github:erstarr
github:fxzzi
github:UjinT34
github:kolayne
github:ikalco

# Third party, passed vouch

github:danielkrupinski
github:LRitzdorf
github:Dregu
github:andresilva
github:zacoons
github:MightyPlaza
github:thejch
github:ItsOhen
github:zjeffer
github:alba4k
github:VirtCode
github:Aqa-Ib
github:Kam1k4dze
github:LionHeartP
github:frebib
github:umbrageodotus
github:mikomikotaishi
github:tyvsmith
github:3y3p4tch
github:aurelleb
github:BlueZeeKing
github:willmtemple

# Denounced

