strikers:

closers:
  - wabarTM
  - LRitzdorf
  - tekstryder


moderators:
  - vaxerski
  - erstarr
  - fufexan
  - notashelf
  - outfoxxed
  - pointerdilemma
  - vdawg-git
  - gulafaran
  - fxzzi
  - UjinT34
  - kolayne
  - ikalco